routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin panel routes for your application.
| These routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('admin.dashboard.index'); })->name('dashboard');
Route::resource('users', 'UserController');

/*
 *  Group routes
 */
Route::resource('groups', 'GroupController');
Route::get('/groups/{group}/add', 'GroupController@addMember')->name('groups.members.add');
Route::post('/groups/{group}/add/{user}', 'GroupController@storeMember')->name('groups.members.store');
Route::post('/groups/{group}/remove/{user}', 'GroupController@removeMember')->name('groups.members.remove');

Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () { return view('admin.dashboard.demo'); });

Auth::routes();

Route::get('/user/{user}', 'UserController@show')->name('profile');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/components/menu.blade.php
<li class="nav-item mT-30 active">
    <a class="sidebar-link" href="{{ route('admin.dashboard') }}">
    <span class="icon-holder">
        <i class="c-blue-500 ti-home"></i>
    </span>
    <span class="title">Dashboard</span>
    </a>
</li>
<li class="nav-item">
    <a class='sidebar-link' href="{{ route('admin.users.index') }}">
    <span class="icon-holder">
        <i class="c-brown-500 ti-user"></i>
    </span>
    <span class="title">Users</span>
    </a>
</li>
<li class="nav-item">
    <a class='sidebar-link' href="{{ route('admin.groups.index') }}">
    <span class="icon-holder">
        <i class="c-yellow-500 ti-layers-alt"></i>
    </span>
    <span class="title">Groups</span>
    </a>
</li>

resources/views/admin/components/messages.blade.php
@if (Session::has('errors'))
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
        </button>
        <ul class="list-unstyled">
            @foreach (Session::get('errors')->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if (Session::has('warning'))
    <div class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
        </button>
        {{Session::get('warning')}}
    </div>
@endif

@if (Session::has('info'))
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
        </button>
        {{Session::get('info')}}
    </div>
@endif

@if (Session::has('success'))
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
        </button>
        {{Session::get('success')}}
    </div>
@endif

resources/views/admin/components/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-inner">
        <!-- ### $Sidebar Header ### -->
        <div class="sidebar-logo">
            <div class="peers ai-c fxw-nw">
                <div class="peer peer-greed">
                    <a class="sidebar-link td-n" href="index.html">
                        <div class="peers ai-c fxw-nw">
                            <div class="peer">
                                <div class="logo">
                                    <img src="{{ asset('images/logo.png') }}" alt="">
                                </div>
                            </div>
                            <div class="peer peer-greed">
                                <h5 class="lh-1 mB-0 logo-text">{{ config('app.name', 'Admin Panel') }}</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="peer">
                    <div class="mobile-toggle sidebar-toggle">
                        <a href="" class="td-n">
                    <i class="ti-arrow-circle-left"></i>
                  </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- ### $Sidebar Menu ### -->
        <ul class="sidebar-menu scrollable pos-r">
            @include('admin.components.menu')
        </ul>
    </div>
</div>

resources/views/admin/components/spinner.blade.php
<div id='loader'>
    <div class="spinner"></div>
</div>

<script>
    window.addEventListener('load', () => {
        const loader = document.getElementById('loader');
        setTimeout(() => {
          loader.classList.add('fadeOut');
        }, 300);
      });
</script>

resources/views/admin/components/topbar.blade.php
<div class="header navbar">
    <div class="header-container">
        <ul class="nav-left">
            <li>
                <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
                    <i class="ti-menu"></i>
                </a>
            </li>
            <li class="search-box">
                <a class="search-toggle no-pdd-right" href="javascript:void(0);">
                    <i class="search-icon ti-search pdd-right-10"></i>
                    <i class="search-icon-close ti-close pdd-right-10"></i>
                </a>
            </li>
            <li class="search-input">
                <input class="form-control" type="text" placeholder="Search...">
            </li>
        </ul>
        <ul class="nav-right">
            <li class="notifications dropdown">
                <span class="counter bgc-red">3</span>
                <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
                    <i class="ti-bell"></i>
                </a>

                <ul class="dropdown-menu">
                    <li class="pX-20 pY-15 bdB">
                        <i class="ti-bell pR-10"></i>
                        <span class="fsz-sm fw-600 c-grey-900">Notifications</span>
                    </li>
                    <li>
                        <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                            <li>
                                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                                    <div class="peer mR-15">
                                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                                    </div>
                                    <div class="peer peer-greed">
                                        <span>
                                            <span class="fw-500">John Doe</span>
                                            <span class="c-grey-600">liked your
                                                <span class="text-dark">post</span>
                                            </span>
                                        </span>
                                        <p class="m-0">
                                            <small class="fsz-xs">5 mins ago</small>
                                        </p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                                    <div class="peer mR-15">
                                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                                    </div>
                                    <div class="peer peer-greed">
                                        <span>
                                            <span class="fw-500">Moo Doe</span>
                                            <span class="c-grey-600">liked your
                                                <span class="text-dark">cover image</span>
                                            </span>
                                        </span>
                                        <p class="m-0">
                                            <small class="fsz-xs">7 mins ago</small>
                                        </p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                                    <div class="peer mR-15">
                                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                                    </div>
                                    <div class="peer peer-greed">
                                        <span>
                                            <span class="fw-500">Lee Doe</span>
                                            <span class="c-grey-600">commented on your
                                                <span class="text-dark">video</span>
                                            </span>
                                        </span>
                                        <p class="m-0">
                                            <small class="fsz-xs">10 mins ago</small>
                                        </p>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="pX-20 pY-15 ta-c bdT">
                        <span>
                            <a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications
                                <i class="ti-angle-right fsz-xs mL-10"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </li>
            <li class="notifications dropdown">
                <span class="counter bgc-blue">3</span>
                <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
                    <i class="ti-email"></i>
                </a>

                <ul class="dropdown-menu">
                    <li class="pX-20 pY-15 bdB">
                        <i class="ti-email pR-10"></i>
                        <span class="fsz-sm fw-600 c-grey-900">Emails</span>
                    </li>
                    <li>
                        <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                            <li>
                                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                                    <div class="peer mR-15">
                                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                                    </div>
                                    <div class="peer peer-greed">
                                        <div>
                                            <div class="peers jc-sb fxw-nw mB-5">
                                                <div class="peer">
                                                    <p class="fw-500 mB-0">John Doe</p>
                                                </div>
                                                <div class="peer">
                                                    <small class="fsz-xs">5 mins ago</small>
                                                </div>
                                            </div>
                                            <span class="c-grey-600 fsz-sm">
                                                Want to create your own customized data generator for your app...
                                            </span>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                                    <div class="peer mR-15">
                                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                                    </div>
                                    <div class="peer peer-greed">
                                        <div>
                                            <div class="peers jc-sb fxw-nw mB-5">
                                                <div class="peer">
                                                    <p class="fw-500 mB-0">Moo Doe</p>
                                                </div>
                                                <div class="peer">
                                                    <small class="fsz-xs">15 mins ago</small>
                                                </div>
                                            </div>
                                            <span class="c-grey-600 fsz-sm">
                                                Want to create your own customized data generator for your app...
                                            </span>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                                    <div class="peer mR-15">
                                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                                    </div>
                                    <div class="peer peer-greed">
                                        <div>
                                            <div class="peers jc-sb fxw-nw mB-5">
                                                <div class="peer">
                                                    <p class="fw-500 mB-0">Lee Doe</p>
                                                </div>
                                                <div class="peer">
                                                    <small class="fsz-xs">25 mins ago</small>
                                                </div>
                                            </div>
                                            <span class="c-grey-600 fsz-sm">
                                                Want to create your own customized data generator for your app...
                                            </span>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="pX-20 pY-15 ta-c bdT">
                        <span>
                            <a href="email.html" class="c-grey-600 cH-blue fsz-sm td-n">View All Email
                                <i class="fs-xs ti-angle-right mL-10"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
                    <div class="peer mR-10">
                        <img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/10.jpg" alt="">
                    </div>
                    <div class="peer">
                        <span class="fsz-sm c-grey-900">John Doe</span>
                    </div>
                </a>
                <ul class="dropdown-menu fsz-sm">
                    <li>
                        <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                            <i class="ti-settings mR-10"></i>
                            <span>Setting</span>
                        </a>
                    </li>
                    <li>
                        <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                            <i class="ti-user mR-10"></i>
                            <span>Profile</span>
                        </a>
                    </li>
                    <li>
                        <a href="email.html" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                            <i class="ti-email mR-10"></i>
                            <span>Messages</span>
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                            <i class="ti-power-off mR-10"></i>
                            <span>Logout</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>